export const actionTypes = {
  SET_SESSION_LOADING: "SET_SESSION_LOADING",
  SET_SESSION_DATA: "SET_SESSION_DATA",
  SET_CARDS_LOADING: "SET_CARDS_LOADING",
  SET_CARDS_DATA: "SET_CARDS_DATA",
  CLEAR_CARDS: "CLEAR_CARDS",
};

export default actionTypes;
